### ISSUE TITLE
[Feature Request] Make the field available as a column in the element index

### ISSUE THREAD

**Issue by benface** [Nav33d/craft-relations#10]
It would be sweet if we could see how many relations an element has right from the index table, by adding a column for the field when customizing sources. It would basically do the same thing as [this plugin](https://github.com/born05/craft-assetusage), but even better as Relations can actually show where assets are used. The field type would have to implement the `PreviewableFieldInterface` interface and extend the `getTableAttributeHtml()` method.

Thank you!

**Comment by Nav33d** [comment]
@benface Thank you for suggesting this. This is something which I have been wanting to do for sometime to be honest with you. How do you imagine it working:

- Only show the relations count on the index table
- Or also the ability to view the relations when clicked or hovered over the relations count?

Let me know your thoughts

**Comment by benface** [comment]
I think by default only the relations count should be shown, but yes, it would be awesome if we could view the relations when hovering or clicking on the count. Would that require more DB queries? If it's too complicated, I'm fine with just the count, I think it would already be a big improvement.

**Comment by Nav33d** [comment]
I have just released [1.2.0](https://github.com/Nav33d/craft-relations/releases/tag/1.2.0) which adds the ability to view relations count on the index table. Hopefully will add the ability to view relations from index table in the future :)
