### ISSUE TITLE
Entry revisions showing up as related entries

### ISSUE THREAD

**Issue by Joobs** [Nav33d/craft-relations#11]
Craft 3.2.9, Relations 1.2.0

I have EntryA and related EntryB via an Entries field.
I carry on editing EntryA, and create 5 revisions. 

When I go to EntryB I now see it related to EntryA 5 times. In think it should only show relations to "current" entries - showing only 1 relation to EntryA

**Comment by Nav33d** [comment]
Hi @Joobs Apologies for delayed reply, I have just had a look and it cannot seem to replicate the issue. I have created many revisions but it doesn't duplicate relations.

It may be that the entry exists in database multiple times with different Ids. Is it possible that you can send me the database and I can take a look?

Many thanks

**Comment by Joobs** [comment]
I've recreated it on a fresh install of Craft 3.2.10. 

I'll email the database over to you

**Comment by romainwurtz** [comment]
Created a pull request #12 with a fix.

**Comment by benface** [comment]
I am seeing this as well.

**Comment by Nav33d** [comment]
Sorry folks for delay on this. Just been super busy with work. Thank you so much @romainwurtz

**Comment by benface** [comment]
I'm still experiencing this issue even after updating to the latest version :(

**Comment by romainwurtz** [comment]
New pull request to fix the issue with draft versions being shown. #15
