### ISSUE TITLE
Trying to get property 'id' of non-object

### ISSUE THREAD

**Issue by piotrpog** [Nav33d/craft-relations#3]
When i add relations entry to section and enter entry editing view, i get the message:

```
yii\base\ErrorException: Trying to get property 'id' of non-object in C:\xampp\htdocs\test2\vendor\nav33d\craft-relations\src\services\Relations.php:57

48495051525354555657585960616263646566                     
            if ( method_exists($relatedElement, 'getOwner') && $relatedElement->getOwner() )
            {
                while ( method_exists($relatedElement, 'getOwner') )
                {
                    $relatedElement = $relatedElement->getOwner();
                }
            }
 
            if ( !isset($relatedElements[$relatedElement->id]) )
            {
                $relatedElements[$relatedElement->id] = $relatedElement;
            }
        }
 
        return $relatedElements;
    }
 
}
                
```
I think important fact is that i did not get this error at first. But after i installed your plugin, i switched craft version to pro and added some users and gave them permission to edit this section. Maybe it has something to do with this?

**Comment by Nav33d** [comment]
Could you please let me know your section fields and where do you have the relations field?

Many thanks

**Comment by piotrpog** [comment]
@Nav33d 
WIll project config file suffice?
https://pastebin.com/HTnKNpd3

**Comment by john-henry** [comment]
@Nav33d I have just run into this error also. Relations field in a tab 

There are also Assets, Matrix, Plain Text, Entries

Other entries seem to work. Have had to disable plugin for client

Craft CMS 3.1.3

**Comment by romainwurtz** [comment]
Same issue on my end. I believe it is happening when the related element has been soft deleted and is still in the trash.

**Comment by john-henry** [comment]
Nothing in our trash and same issue

**Comment by romainwurtz** [comment]
Interesting. Created a pull request #5 with a (quick) fix that resolved the issue on my end.

**Comment by Nav33d** [comment]
@romainwurtz Thank you for the pull request.

@john-henry @piotrpog The issue should be fixed now.
