### ISSUE TITLE
Q: Does this only show reverse-relations in the CP?

### ISSUE THREAD

**Issue by swthate** [Nav33d/craft-relations#6]
As the subject says, does this only show reverse-relationships for a given entry in the CP? Can this field be queried from a `_entry.twig` template to get any reverse-relationships for that given entry on the frontend as well?

A "Usage" section on the documentation would be helpful, if applicable.

Thanks!

**Comment by Nav33d** [comment]
Yes, it should be possible to show related entries within the template. I will have this available in the next release.

**Comment by Nav33d** [comment]
This is now possible in version `1.1.0`. I have also update README with instructions.
