### ISSUE TITLE
"Relations may only contain a maximum of 255 characters"

### ISSUE THREAD

**Issue by ul8** [Nav33d/craft-relations#7]
Above error message is displayed when saving the relations field after updating to Plugin version 1.1.0. (I roughly translated the message from German..)

Downgrade to 1.0.3 fixes the issue for me.

I'm on Craft CMS 3.1.22

Thanks!

**Comment by Nav33d** [comment]
Hey, Thank you for reporting this error. I have pushed an update to fix this. Hopefully didn't break anything else 😄
