### ISSUE TITLE
Relations in Structure seems not to be working

### ISSUE THREAD

**Issue by steve71p** [Nav33d/craft-relations#8]
Hi,
I added a Relation field in a Section: Type Structure and I get "no relations found".
I did the same with a Section: Type Channel and Single and it works fine.
Using Craft 3.0.41.1, I did a test also with Craft 3.1.22 and I have the same issue.

Do you have any suggestions? Could it be a bug?

Thank you very much
Steve

**Comment by Nav33d** [comment]
@steve71p I Just did a test and seems to work fine. Are entries in your structure related somewhere? It will show `no relations found` if they are not.

**Comment by steve71p** [comment]
Hi, Yes I do have entries related, it's strange but if with you it's working I will do a double check and see if I'm not doing something wrong.

**Comment by Nav33d** [comment]
No worries, let me know if there is an issue. It would also be good to know if entries are being related within another field like Neo or Super Table.

**Comment by steve71p** [comment]
I have a channel "teachers" and I have a stucture "courses". In an entry "course" I have an "entries field" to select a teacher.
In the channel "teacher" I add your relation field but it doesn't show the related course.
Keep in mind I'm in a multisite enviroment.

**Comment by Nav33d** [comment]
@steve71p I tried to replicate this issue but no success so far. Could you please send me a test db which I run on my machine to replicate this issue?
